# Generated by Django 4.2.26 on 2025-11-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="task",
            name="column",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CHECKING", "Checking"),
                    ("DONE", "Done"),
                    ("REJECTED", "Rejected"),
                    ("BUGFIX", "Bug Fix"),
                    ("RELEASED", "Released"),
                ],
                default="TODO",
                help_text="Текущая колонка на Kanban-доске",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
